### ISSUE TITLE
There may be mismatch on the choice of input

### ISSUE THREAD

**Issue by IDKiro** [HuiZeng/Image-Adaptive-3DLUT#19]
![image](https://user-images.githubusercontent.com/24263261/95984711-33904000-0e56-11eb-895d-90e2419c39f9.png)

As far as I know, the Input setting used in the DeepUPE experiment is (default), and I downloaded the sample you provided, I found that the Input used in your experiment is the fourth (highlighted).
The default input setting is darker than the fourth input setting, which may be the reason why your method SSIM is particularly high. 
In addition, your train/test split setting of FIVEK dataset is also inconsistent with DeepUPE. Considering that DeepUPE does not share the training code, I would like to know whether you have re-implemented and trained the DeepUPE model?

The input of a5000 in your work:
![lut5000](https://user-images.githubusercontent.com/24263261/95986545-c7630b80-0e58-11eb-9aec-9fa79d2a5f6b.jpeg)

The input of a5000 in DeepUPE:
![a5000-kme_0204](https://user-images.githubusercontent.com/24263261/95986590-d944ae80-0e58-11eb-9493-d1b85d0b56a2.jpg)

**Comment by HuiZeng** [comment]
Since photo retorching is a relatively small task. Previsous methods use several different settings including training/testing splits, color space, dynamic range (8 bits or 16 bits), paired/unpaired training. 
In my expriments, most of the settings were following deep photo enhance (DPE), which provide both paired and unpaired splits as well as detailed discussions on the input format. 
I asked the authors of DeepUPE for their training code and had many discussion with the authors during my re-implementation.
For some reason, they did not release their training code and dataset.
For the SSIM index, there are usually two types of implementation. When using the origianl source code provided by Zhou Wang, it will downsample input image large than 256 pixels, which is much faster and usually results in much higher value than the that calculated on the original resolution.

**Comment by HuiZeng** [comment]
For fair comparison, all comparing methods were re-trained and evaluated under the same setting using the same split.
You can also train a new model using the provided training code for your own purpose.

**Comment by IDKiro** [comment]
Indeed, as you said, differences in experimental settings make it difficult to compare experimental results.
You have addressed my concern and I'll close the issue.
Thanks！
