### ISSUE TITLE
Different SSIM results between matlab and python-skimage

### ISSUE THREAD

**Issue by hkzhang95** [HuiZeng/Image-Adaptive-3DLUT#30]
Hi, I am trying to replace the matlab evaluation script with python style for some reason. Then I do something like this:

```python
from skimage.metrics import structural_similarity as img_ssim
# To match the implementation of Wang et. al. [1]_, set `gaussian_weights` to True, `sigma` to 1.5, and `use_sample_covariance` to False.
ssim_val = img_ssim(test_img, gt_img, multichannel=True, data_range=255.0, gaussian_weights=True, sigma=1.5, use_sample_covariance=False)
```

However, the results are as follows ('for a4994.png'):

- [skimage (v0.16.2)](https://github.com/scikit-image/scikit-image/blob/v0.16.x/skimage/metrics/_structural_similarity.py#L12): 0.926184
- matlab (octave v4.2.2): 0.951937

Could you please tell me where is the difference between the implementations of the two versions? Or can you provide a python script for evaluating SSIM and Lab?

Thank you very much.

**Comment by HuiZeng** [comment]
Calculating SSIM on high-resolution images is very slow. The original implementation by Zhou Wang thus downsample the image resolution to speed up the calculation. Downsampling usually leads to higher SSIM index.
According to my experience, the difference of SSIM index is usually caused by different downsampling strategies.

**Comment by hkzhang95** [comment]
Ok, thanks for your comments.
